//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Risk()
        {
            this.RiskImpacts = new HashSet<RiskImpact>();
            this.RiskMitigations = new HashSet<RiskMitigation>();
        }
    
        public int RiskId { get; set; }
        public int Year { get; set; }
        public string ProcessBusiness { get; set; }
        public string RiskCategory { get; set; }
        public string RiskEvent { get; set; }
        public string RiskAgent { get; set; }
        public string KRI { get; set; }
        public string Controll { get; set; }
        public string QualitatifImpact { get; set; }
        public string RiskClasification { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string QualitatifQuantitatifRisk { get; set; }
        public string RiskNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskImpact> RiskImpacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskMitigation> RiskMitigations { get; set; }
    }
}
