//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskImpact
    {
        public int ImpactId { get; set; }
        public int RiskId { get; set; }
        public string Type { get; set; }
        public Nullable<double> QuantitatifImpact { get; set; }
        public Nullable<int> Probability { get; set; }
        public Nullable<int> Impact { get; set; }
        public Nullable<int> RPN { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> QuantitatifImpactRes { get; set; }
        public Nullable<int> ProbabilityRes { get; set; }
        public Nullable<int> ImpactRes { get; set; }
        public Nullable<int> RPNRes { get; set; }
    
        public virtual Risk Risk { get; set; }
    }
}
